### ISSUE TITLE
Docs: `appendContentOnMatchOnly` unclear

### ISSUE THREAD

**Issue by mildmojo** [nefrob/pr-description#15]
I'm using the action to replace placeholders in PR descriptions, and I was surprised when it appended those replacements to the end of the description when there were no regex matches found.

Ideally, replace-only-if-found would be the default, and a positive flag like `appendIfNoMatch` would control appending. Otherwise, I think it would help to document the `appendContentOnMatchOnly` option by describing its effect instead of the opposite of its effect. Current docs:

> appendContentOnMatchOnly: Whether to append the content to the PR body if no matches are found. Defaults to "false".

It does control that behavior, but the way it's documented, it sounds like the default is _not_ to append when no matches are found, which is not how it works. The default is to append when no matches are found, and `true` disables the append. I'd suggest something more like:

> appendContentOnMatchOnly: Skip appending content if no regex matches are found. Defaults to "false".

**Comment by nefrob** [comment]
That's for flagging this. I can make the docs update soon. 

As far as the default, the `appendContentOnMatchOnly` input was only added recently so I maintained the old default behavior of always appending for backwards compatibility with existing users of the action. This could be tweaked in a minor/major version bump in the future if desired.

**Comment by nefrob** [comment]
@mildmojo please see https://github.com/nefrob/pr-description/pull/16. Feel free to drop any additional feedback here or on the pull request directly.

**Comment by mildmojo** [comment]
>As far as the default, the appendContentOnMatchOnly input was only added recently so I maintained the old default behavior of always appending for backwards compatibility with existing users of the action. This could be tweaked in a minor/major version bump in the future if desired.

I do think behavior would be less surprising if `regex` implied only replacing on a match, but I understand the backward-compatibility concern. I'm one person, but I think it would be a good change, and a major version bump seems appropriate.

Thanks for looking at this!
